name: aur-release

on:
  workflow_dispatch:

jobs:
  aur-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release AUR package
        uses: jbouter/aur-releaser@v0.0.9
        with:
          pkgname: ttf-apple-emoji
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.USERNAME }}
          commit_email: ${{ secrets.EMAIL }}
          ssh_private_key: ${{ secrets.SSH }}
          commit_message: publish ttf-apple-emoji
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
